import MahjongTile from "@/types/MahjongTile";

const CharacterTiles: MahjongTile[] = [
  {
    id: "1c",
    nameCantonese: "一萬",
    nameEnglish: "1 Character",
    category: "characters",
    unicode: "🀇",
    pinyin: "yat1 maan6",
  },
  {
    id: "2c",
    nameCantonese: "二萬",
    nameEnglish: "2 Characters",
    category: "characters",
    unicode: "🀈",
    pinyin: "yi6 maan6",
  },
  {
    id: "3c",
    nameCantonese: "三萬",
    nameEnglish: "3 Characters",
    category: "characters",
    unicode: "🀉",
    pinyin: "saam1 maan6",
  },
  {
    id: "4c",
    nameCantonese: "四萬",
    nameEnglish: "4 Characters",
    category: "characters",
    unicode: "🀊",
    pinyin: "sei3 maan6",
  },
  {
    id: "5c",
    nameCantonese: "五萬",
    nameEnglish: "5 Characters",
    category: "characters",
    unicode: "🀋",
    pinyin: "ng5 maan6",
  },
  {
    id: "6c",
    nameCantonese: "六萬",
    nameEnglish: "6 Characters",
    category: "characters",
    unicode: "🀌",
    pinyin: "luk6 maan6",
  },
  {
    id: "7c",
    nameCantonese: "七萬",
    nameEnglish: "7 Characters",
    category: "characters",
    unicode: "🀍",
    pinyin: "cat1 maan6",
  },
  {
    id: "8c",
    nameCantonese: "八萬",
    nameEnglish: "8 Characters",
    category: "characters",
    unicode: "🀎",
    pinyin: "baat3 maan6",
  },
  {
    id: "9c",
    nameCantonese: "九萬",
    nameEnglish: "9 Characters",
    category: "characters",
    unicode: "🀏",
    pinyin: "gau2 maan6",
  },
];
export default CharacterTiles;